### ISSUE TITLE
The /att slash command doesn't exist

### ISSUE THREAD

**Issue by ShaunDreclin** [lcs2142/AdvancedTooltips#2]
When you do `/advancedtooltips stats`, you get `Usage: /att stats (on|off)` but /att isn't a slash command.

**Comment by lcs2142** [comment]
Yeah, it turns out '/att` is registered by [ALL THE THINGS](https://wow.curseforge.com/projects/all-the-things) and I didn't want to step on it. I'll remove the reference from that in the next build.
